server:
  url: $SERVICE_URL
  front_port: $FRONTEND_PORT
  port: $BACKEND_PORT

db:
  type: 'postgres'
  port: $POSTGRES_PORT
  database: $POSTGRES_DB

jwt:
  expiresIn: $JWT_EXPIRES_IN

intra:
  grant_type: 'authorization_code'
  client_id: $CLIENT_ID
  client_secret: $CLIENT_SECRET
  redirect_uri: $REDIRECT_URI
