version: '3.9'

services:

  db:
    image: postgres:15.4
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - tsen-net

  backend:
    build: ./backend
    container_name: backend
    image: backend
    depends_on:
      - db
    ports:
      - 3000:3000
    restart: always
    networks:
      - tsen-net
networks:
  tsen-net:
    driver: bridge